In [1]:
class Student:
    def __init__(self, name, age):
        self._name = name
        self._age = age
        self.grades = []

    @property
    def name(self):
        return self._name
    @property
    def age(self):
        return self._age
    
    @name.setter
    def name(self, name):
        self._name = name
    @age.setter
    def age(self, age):
        if age > 0:
            self._age = age
        else:
            raise ValueError("Age must be positive")
        
    # method to add grades
    def add_grade(self, grade):
        if 0 <= grade <= 100:
            self.grades.append(grade)
        else:
            raise ValueError("Grade must be between 0 and 100")
    
    # method to calculate average grade
    def calculate_average(self):
        if len(self.grades) == 0:
            return 0
        return sum(self.grades) / len(self.grades)
    
    # method to describe the student
    def describe(self):
        return f"Student Name: {self.name}, Age: {self.age}, Average Grade: {self.calculate_average():.2f}"

In [ ]:
class School:
    def __init__(self):
        self.students = []

    # method to add students
    def add_student(self, student):
        self.students.append(student)

    # method to remove students
    def remove_student(self, name):
        self.students = [student for student in self.students if student.name != name]

    # method to find student by name
    def find_student(self, name):
        for student in self.students:
            if student.name == name:
                return student
        return None
            
    # method return average grade of all students
    def get_top_student(self):
        if len(self.students) == 0:
            return "No students in School!"
        top_student = max(self.students, key=lambda student: student.calculate_average())
        return top_student.describe()

In [12]:
import pandas as pd
import numpy as np

num_students = 100

names = [f"Student {i+1}" for i in range(num_students)]

# Tạo tuổi ngẫu nhiên từ 15 đến 18
ages = np.random.randint(15, 19, size=num_students)

# Tạo điểm số ngẫu nhiên từ 0 đến 100
maths_grades = np.random.uniform(0, 100, size=num_students)
physics_grades = np.random.uniform(0, 100, size=num_students)
chemistry_grades = np.random.uniform(0, 100, size=num_students)

# Tạo DataFrame
students_df = pd.DataFrame({
    'Name': names,
    'Age': ages,
    'Maths': maths_grades,
    "Physics": physics_grades,
    "Chemistry": chemistry_grades
    
})
students_df.head()

        Name  Age      Maths    Physics  Chemistry
0  Student 1   18  67.868617  92.946040  32.872786
1  Student 2   18  62.009785  67.028761   0.563281
2  Student 3   18  89.492755  50.643162  18.648561
3  Student 4   15  69.043284  71.261267  19.252225
4  Student 5   16   6.547856  89.368061  67.650411

In [ ]:
school = School()

# Transfer data from DataFrame to School object
for index, row in students_df.iterrows():
    student = Student("", 0)
    student.name = row['Name']
    student.age = row['Age']
    student.add_grade(row['Maths'])
    student.add_grade(row['Physics'])
    student.add_grade(row['Chemistry'])
    school.add_student(student)

# compoute the average grade of first 10 students
for i in range(10):
    print(school.students[i].describe())

# check the top student
print("\nStudent with highest average grade:")
print(school.get_top_student())

# check the student by name "Student 10"
print("")
print(school.find_student("Student 10").describe())

# remove student by name "Student 10"
school.remove_student("Student 10")
st10 = school.find_student("Student 10")
if st10 is None:
    print("Student 10 is removed")

Student Name: Student 1, Age: 18, Average Grade: 64.56
Student Name: Student 2, Age: 18, Average Grade: 43.20
Student Name: Student 3, Age: 18, Average Grade: 52.93
Student Name: Student 4, Age: 15, Average Grade: 53.19
Student Name: Student 5, Age: 16, Average Grade: 54.52
Student Name: Student 6, Age: 16, Average Grade: 68.07
Student Name: Student 7, Age: 16, Average Grade: 39.57
Student Name: Student 8, Age: 18, Average Grade: 38.24
Student Name: Student 9, Age: 17, Average Grade: 65.50
Student Name: Student 10, Age: 18, Average Grade: 68.80

Student with highest average grade:
Student Name: Student 94, Age: 18, Average Grade: 96.51

Student Name: Student 10, Age: 18, Average Grade: 68.80
Student 10 is removed